BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Student_Course` (
	`studentID`	INTEGER NOT NULL,
	`teacherID`	INTEGER NOT NULL,
	FOREIGN KEY(`studentID`) REFERENCES `Student`(`ID`),
	FOREIGN KEY(`teacherID`) REFERENCES `Teacher`(`ID`)
);
CREATE TABLE IF NOT EXISTS `Course` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`teacherID`	TEXT NOT NULL,
	FOREIGN KEY(`teacherID`) REFERENCES `Teacher`(`ID`)
);
CREATE TABLE IF NOT EXISTS `Student` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Teacher` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`email`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL
);
COMMIT;
